# Generated by Django 3.1.7 on 2021-03-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0002_auto_20210313_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieseance',
            name='seance_duration',
        ),
        migrations.RemoveField(
            model_name='movieseance',
            name='show_duration',
        ),
        migrations.AddField(
            model_name='movieseance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='movieseance',
            name='show_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movieseance',
            name='start_time_seance',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
