# Generated by Django 3.1.7 on 2021-03-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0003_auto_20210314_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieseance',
            name='free_seats',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
