# Generated by Django 3.1.7 on 2021-03-16 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0004_movieseance_free_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buying',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_movie', to='cinema_app.movieseance'),
        ),
        migrations.AlterField(
            model_name='buying',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
